server:
  port: 8087

spring:
  application:
    name: dubbo-hmily-tcc-client

dubbo:
  scan:
    base-packages: com.sqifun.jtc.week9.controller
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181