spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: shop-0, shop-1
      shop-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://43.129.216.41:3306/shop_0?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      shop-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://43.129.216.41:3306/shop_0?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
    sharding:
      tables:
        order_info:
          actualDataNodes: shop_${0..1}.order_info_${0..15}
          tableStrategy:
            standard:
              shardingColumn: number
              shardingAlgorithmName: t_order_inline
        defaultDatabaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database_inline
        defaultTableStrategy:
          none:
        shardingAlgorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: shop_${user_id % 2}
          t_order_inline:
            type: INLINE
            props:
              algorithm-expression: order_info_${number % 16}